apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: fountainorg/${{ values.destination | dump }}
    backstage.io/kubernetes-id: ${{ values.name | dump }}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{ values.name | dump }}
  links:
    - url: https://whale-simple-mule.ngrok-free.app
      title: somos-test-app
      icon: dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental

